#!/usr/bin/ruby

class Profile

	def initialize(homedirectory)
		@profile_location = homedirectory
	end

	def profile_location
		@profile_location
	end

	def find_profiles
		profiles = []

		if profile_exists(".bashrc")
			profiles << :bashrc
		end

		if profile_exists(".kshrc")
			profiles << :kshrc
		end

		if profile_exists(".bash_profile")
			profiles << :bash_profile
		end

		return profiles
	end

	def self.generate_alias(destination)
		File.write(destination + "/.alias", "# autogenerated .alias file")
	end

	private
	def profile_exists(profile_filename)
		return FileTest.file?(@profile_location + "/" + profile_filename)
	end
end



