
require 'rspec'
require "../lib/profile/profile.rb"

describe Profile do

	before do
		@destination = "testdir"
	end

	it "should be able to create an alias file" do
		filename = ".alias"
		fully_qualified_filename = @destination + "/" + filename

		if File.exists?(fully_qualified_filename)
			File.delete(fully_qualified_filename)
		end

		Profile.generate_alias(@destination)

		expect(File.exists?(fully_qualified_filename)).to be true
	end

	it "should tell me what kind of profile files are available" do
		create_test_file(".bash_profile")
		create_test_file(".bashrc")
		create_test_file(".kshrc")

		profile = Profile.new(@destination)

		profile_types = profile.find_profiles
		expect(profile_types.include?(:bash_profile)).to be true
		expect(profile_types.include?(:bashrc)).to be true
		expect(profile_types.include?(:kshrc)).to be true
	end

	private
	def create_test_file(filename)
		File.write(@destination + "/" + filename, "autogenerated " + filename + " file")
	end
end
