require 'spec_helper'
require_relative "../lib/aliai/profile"

describe Profile do

  it "should generate an alias file in the given directory" do
    expect(File).to receive(:write).with("testdir/.alias", "# autogenerated .alias file")
    Profile.generate_alias('testdir')
  end

  it "should tell me what kind of profile files are available" do
    expect(FileTest).to receive(:file?).with("testdir/.bash_profile") { true }
    expect(FileTest).to receive(:file?).with("testdir/.bashrc") { true }
    expect(FileTest).to receive(:file?).with("testdir/.kshrc") { true }

    profile = Profile.new('testdir')

    profile_types = profile.find_profiles

    expect(profile_types.include?(:bash_profile)).to be true
    expect(profile_types.include?(:bashrc)).to be true
    expect(profile_types.include?(:kshrc)).to be true
  end

end
